export const FETCH_EMPLOYMENTS_REQUEST = 'FETCH_EMPLOYMENTS_REQUEST';
export const FETCH_EMPLOYMENTS_SUCCESS = 'FETCH_EMPLOYMENTS_SUCCESS';
export const FETCH_EMPLOYMENTS_FAILURE = 'FETCH_EMPLOYMENTS_FAILURE';

export const FETCH_GET_OFFER_REQUEST = 'FETCH_GET_OFFER_REQUEST';
export const FETCH_GET_OFFER_SUCCESS = 'FETCH_GET_OFFER_SUCCESS';
export const FETCH_GET_OFFER_FAILURE = 'FETCH_GET_OFFER_FAILURE';
