export const FETCH_FOLLOW_ENTERPRISES = 'FETCH_FOLLOW_ENTERPRISES';
export const FETCH_FAILED_FOLLOW_ENTERPRISES = 'FETCH_FAILED_FOLLOW_ENTERPRISES';
export const FETCH_SUCCESS_FOLLOW_ENTERPRISES = 'FETCH_SUCCESS_FOLLOW_ENTERPRISES';
export const FETCH_RESET_FOLLOW_ENTERPRISES = 'FETCH_RESET_FOLLOW_ENTERPRISES';