export const FETCH_GET_APPLICATIONS_REQUEST = 'FETCH_GET_APPLICATIONS_REQUEST';
export const FETCH_GET_APPLICATIONS_SUCCESS = 'FETCH_GET_APPLICATIONS_SUCCESS';
export const FETCH_GET_APPLICATIONS_FAILURE = 'FETCH_GET_APPLICATIONS_FAILURE';
