/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        // Colores personalizados
        'brown1': '#030101',
        'brown2': '#1F0B08',
        'brown3': '#421C18',
        'brown4': '#692D27',
        'brown5': '#8D453D',
        'brown6': '#B15F56',
        'brown7': '#C7847B',
        'brown8': '#D8ABA4',
        'brown9': '#EFCFCA',
        'brown10': '#FFF4F2',
        'techBlue': '#41A5D7',
        'techTurquoise': '#3FD7CD',
        'techPurple': '#9270F1',
        'techGray': '#B3B3B3',
        'skinLight': '#FDBCB4',
        'skinPale': '#FDE4D5',
        'semanticYellow': '#FFCB32',
        'semanticRed': '#E80000',
        'semanticDarkTurquoise': '#0A2229',
        'semanticGreen': '#BD31CB',
        'skinTone1': '#401A1A',
        'skinTone2': '#5C2A2A',
        'skinTone3': '#733E3E',
        'skinTone4': '#8A5555',
        'skinTone5': '#A16D6D',
        'skinTone6': '#B98585',
        'skinTone7': '#D09E9E',
        'skinTone8': '#E7B7B7',
        'skinTone9': '#FFCECE',
        //colors
        'blue0': '#00476d',
        'sky-blue0': '#81bfec',
        'sky-blue1': '#bdd0fb',
        'sky-blue2': '#1d4ed8',
        'green2': '#d1fbbd',
        'pink4':'#FBD3BD',
        'blue1':'#bddafb',
        'bluec':'#0778B1',
        'gray' : '#52525B',
        'gray2': '#E1E1E2',
        'gray3': '#F4F4F5',
        'gray4': '#CCCCCC',
        // Background Home
        'pink': '#F5B8AC',
        'greene':'#E1E1E2',
        'green12':'#5B5B5C',
        'green22':'#5E5E5E',
        'green32':'#5F5F5F',
        'green42':'#52525B',
        'greenv':'#1E750F',
        'orangeo':'#AF5407',
        'black2':'#1A1A1A',
        'grays':'#A1A1AA',


        // Colors Home
        'blue': '#00476D',
        'blue2': '#023047',
        'blue3': '#006497',
        'blue4': '#81BFEC',
        'blue5': '#F6FAFE',
        'white': '#FFFFFF',
      },
      spacing: {
        '17': '68px',
        '7': '28px',
        '18': '4.5rem',
        '72': '18rem',
        '84': '21rem',
        '96': '24rem',
        '108': '27rem',
        '120': '30rem',
        '132': '33rem',
        '144': '36rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        serif: ['Merriweather', 'ui-serif', 'Georgia'],
        mono: ['Fira Code', 'ui-monospace', 'SFMono-Regular'],
        display: ['Oswald', 'sans-serif'],
        body: ['"Open Sans"', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        playfair: ['"Playfair Display"', 'serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
      },
      screens: {
        'xs': '501px',
        'sm': '590px',
        'md': '767px',
        'lg': '900px',
        'xl': '950px',
        '2xl': '1037px',
        '2x2': '1190px',
        '2x3': '1330px',
      },
      fontSize: {
        'heading-lg': '28px',
        'heading-x1': '18px',
        'body-md': '16px',
        'body-xl': '22px',
        'heading-md': '24px',
        'heading-sm': '20px',
        'body-sm': '14px',
        'body-xs': '15px',
        'caption': '12px',
        'display-lg': '32px',
        'display-xl': '36px',
        'display-2xl': '40px',
        '5xl': '48px'
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        'full': '9999px',
        'large': '12px',
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ['active', 'group-hover'],
      textColor: ['visited'],
      display: ['group-hover'],
    },
  },
};
