export const FETCH_CREATE_OFFER = 'FETCH_CREATE_OFFER';
export const FETCH_FAILED_CREATE_OFFER = 'FETCH_FAILED_CREATE_OFFER';
export const FETCH_SUCCESS_CREATE_OFFER = 'FETCH_SUCCESS_CREATE_OFFER';
export const FETCH_RESET_CREATE_OFFER = 'FETCH_RESET_CREATE_OFFER';