export const FETCH_GET_OFFER_SAVE_REQUEST = 'FETCH_GET_OFFER_SAVE_REQUEST';
export const FETCH_GET_OFFER_SAVE_SUCCESS = 'FETCH_GET_OFFER_SAVE_SUCCESS';
export const FETCH_GET_OFFER_SAVE_FAILURE = 'FETCH_GET_OFFER_SAVE_FAILURE';
