export const FETCH_SAVE_OFFER = 'FETCH_SAVE_OFFER';
export const FETCH_FAILED_SAVE_OFFER = 'FETCH_FAILED_SAVE_OFFER';
export const FETCH_SUCCESS_SAVE_OFFER = 'FETCH_SUCCESS_SAVE_OFFER';
export const FETCH_RESET_SAVE_OFFER = 'FETCH_RESET_SAVE_OFFER';