// constants/offer/SearchOffersEmpl.ts

export const SEARCH_OFFERS_EMPL_REQUEST = 'SEARCH_OFFERS_EMPL_REQUEST';
export const SEARCH_OFFERS_EMPL_SUCCESS = 'SEARCH_OFFERS_EMPL_SUCCESS';
export const SEARCH_OFFERS_EMPL_FAILURE = 'SEARCH_OFFERS_EMPL_FAILURE';
