export const FETCH_SIGNUP_OFFER = 'FETCH_SIGNUP_OFFER';
export const FETCH_FAILED_SIGNUP_OFFER = 'FETCH_FAILED_SIGNUP_OFFER';
export const FETCH_SUCCESS_SIGNUP_OFFER = 'FETCH_SUCCESS_SIGNUP_OFFER';
export const FETCH_RESET_SIGNUP_OFFER = 'FETCH_RESET_SIGNUP_OFFER';